"""Add extra models

Revision ID: 0ffd7cc1420e
Revises: 77f0cae9026c
Create Date: 2024-04-13 14:59:58.989641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ffd7cc1420e'
down_revision: Union[str, None] = '77f0cae9026c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region',
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('region_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('region_id')
    )
    op.create_table('request',
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('home_number', sa.Integer(), nullable=False),
    sa.Column('flat_number', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('contact_first_name', sa.String(), nullable=True),
    sa.Column('contact_last_name', sa.String(), nullable=True),
    sa.Column('contact_phone_number', sa.String(), nullable=True),
    sa.Column('request_text', sa.String(), nullable=False),
    sa.Column('volunteer_id', sa.BigInteger(), nullable=True),
    sa.Column('request_status', sa.Enum('created', 'taken_by_volunteer', 'partially_fulfilled', 'completely_fulfilled', 'delivered', 'accepted_by_user', 'rated_and_ended', name='requeststatus'), nullable=False),
    sa.Column('request_date', sa.DateTime(), nullable=False),
    sa.Column('request_delivery_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['region.region_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('user_region',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('volunteer_region', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['region.region_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'region')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('user_region')
    op.drop_table('request')
    op.drop_table('region')
    # ### end Alembic commands ###
