"""Add delivery_type for request model

Revision ID: 3e26d86cd585
Revises: 0336e6c8ce0f
Create Date: 2024-04-13 23:12:43.396467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e26d86cd585'
down_revision: Union[str, None] = '0336e6c8ce0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('is_delivery', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'is_delivery')
    # ### end Alembic commands ###
