"""Add new field to evacuation model

Revision ID: f481561723d7
Revises: 3e26d86cd585
Create Date: 2024-04-14 03:38:28.323807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f481561723d7'
down_revision: Union[str, None] = '3e26d86cd585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evacuation_request', sa.Column('evacuation_qnt', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evacuation_request', 'evacuation_qnt')
    # ### end Alembic commands ###
